FROM node:22-alpine

RUN apk add --no-cache \
  curl \
  git \
  zsh \
  make

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install -g @nestjs/cli

COPY . .

EXPOSE 3000
# CMD ["tail", "-f", "/dev/null"]
CMD ["npm", "run", "start:dev"]
