services:
  db:
    container_name: challenge-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: challenge-redis
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - NODE_PATH=.
    container_name: challenge-nestjs

volumes:
  postgres_data:
