export enum ContentExtension {
  PDF = 'pdf',
  JPG = 'jpg',
  JPEG = 'jpeg',
  PNG = 'png',
  MP4 = 'mp4',
  MOV = 'mov',
  AVI = 'avi',
  MKV = 'mkv',
  GIF = 'gif',
  DOC = 'doc',
  DOCX = 'docx',
  XLS = 'xls',
  XLSX = 'xlsx',
  PPT = 'ppt',
  PPTX = 'pptx',
  TXT = 'txt',
  ZIP = 'zip',
  RAR = 'rar',
  HTML = 'html',
  CSS = 'css',
  JS = 'js',
  JSON = 'json',
  XML = 'xml',
  MP3 = 'mp3',
  WAV = 'wav',
}
